#+TITLE: learn-haskell
#+AUTHOR: abi (bimorphism)

* Preface
These are just my *personal* notes I'm taking to help myself learn the language.
As such, they may not be fully complete -- or even well documented (compared to other tutorials).

I am also writing them in Org mode since I find it convinient for note taking and I daily-drive emacs,
so your editor of choice will need to be able to display org mode files to view them.

* Basic types
#+begin_src haskell
  let author          = "abi" -- string
  let meaningOfLife   = 42    -- integer (whole numbers)
  let piConstant      = 3.14  -- floats

  -- Integer is like Int but *really really* big
  -- Float and Double are part of Fractional typeclass

  -- Int and Integer are part of Integral typeclass
  -- Num is the base typeclass for *all* numeric types
#+end_src

** Lists
Lists are defined using [ and ]. They can only hold elements that are all of the *same* type -
eg a list of *String* can /only/ hold Strings and nothing else.
#+begin_src haskell
  let someNumbers = [1, 2, 3, 4, 5]            -- [Int]
  let fruits = ["apple", "orange", "banana"]   -- [String]

  -- Strings are just [Char] - it's just an alias
  let aString = "foo bar"

  -- So all the list functions work on strings, and list of type a

  -- List functions
  head someNumbers -- head gets the first item in a list => 1
  tail someNumbers -- tail gets the *rest* of the list => [2,3,4,5]

  -- init gets everything *up to* the end of the list
  init someNumbers -- => [1,2,3,4]

  -- take/drop takes/drops n items from a list
  take 2 someNumbers -- [1,2]
  drop 2 someNumbers -- [3,4,5]

  -- replicate replicates an element n times
  replicate 5 "whee" -- ["whee", "whee", "whee", "whee", "whee"]
#+end_src

** Tuples
Tuples are defined like (a, b). /a/ and /b/ can both have different types.
#+begin_src haskell
  let pair = (1, 'a') -- pair of Int and String

  fst pair -- fst gets the first item  => 1
  snd pair -- snd gets the second item => 'a'

  -- NOTE: There are no functions to get the first, second, third element
  -- of a triple or any larger n-tuples

  -- They can be used in lists!
  let pairs = [(1, 'a'), (2, 'b'), (3, 'c')]
#+end_src
* Guards and Conditionals
If expressions *must* have an else condition since unlike imperative languages,
they are expressions too and they must /always/ return a value of some sort.

#+begin_src haskell
  -- Valid
  if condition then if_value else else_value

  -- Invalid
  if condition then if_value -- no else supplied, if/else needs to return a value!

  -- All comparison operators are available
  -- >, <, <=, >=, = but /= is not equal instead of != like most languages.
#+end_src

** Guards
Guards are syntactic sugar for if expressions.

#+begin_src haskell
  -- Very pointless contrived example since even exists in Prelude but
  tellMeIsItEven :: (Integral a) => a -> String
  tellMeIsItEven n
    | n `mod` 2 == 0 = "yes it is"
    | otherwise      = "no its not"

  -- We could have written this like
  -- But guards make it clearer to write
  tellMeIsItEven' n = if n `mod` 2 == 0 then "yes it is" else "no its not"
#+end_src

* Functions
** Higher order functions
Higher order functions are functions that take other functions as arguments/input.

~filter~ is an example of a higher order function. It's type says it takes a function
~(a -> Bool)~ and a list of ~a~ things and returns back a new list of ~a~ things.

** Currying
All functions are curried in Haskell. What this means is that a function ~a -> a -> a~ can
be expressed as ~a -> (a -> a)~.

Which means that the function takes a /single/ a and returns a *new* function that takes
another /a/ and this function will *eventually* return an /a/ of its own.

Because currying is opt-out, functions can be partially applied (specifying only some of 
their input parameters) so we get a new function back which when called will apply it to the
rest of the arguments.

